targets:
  - name: staging
    args:
      environment: staging
    # Adding a context to .kluctl.yaml helps prevent accidentally deploying to the wrong cluster!
    context: kind-kind

  - name: production
    args:
      environment: production
    # Adding a context to .kluctl.yaml helps prevent accidentally deploying to the wrong cluster!
    context: kind-kind

args:
  - name: environment

discriminator: kluctl-{{ target.name }}
