apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzdW5kYWxlaSIsInBhc3N3b3JkIjoib2FybnVkOUl0ZXN0IiwiZW1haWwiOiJzdW5kYWxlaTE5ODhAZ21haWwuY29tIiwiYXV0aCI6ImMzVnVaR0ZzWldrNmIyRnliblZrT1VsMFpYTjAifX19
