apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-golang
  namespace: demo-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api-golang
          image: sundalei/devops-directive-docker-course-api-golang:staging
