# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: civo-object-store-creds
stringData:
  AWS_ACCESS_KEY_ID: <>
  AWS_SECRET_ACCESS_KEY: <>
  AWS_REGION: us-east-1
