name: image-ci

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"
    # paths:
      # Only rebuild images when applications change
      # - "06-demo-application/**/*"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, world!"

  generate-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate-image-tag.outputs.image_tag}}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # Necessary to get all tags for IMAGE_TAG generation with git describe
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Generate Image Tag
        id: generate-image-tag
        working-directory: 14-cicd/github-actions
        run: |
          image_tag=$(task generate-version-tag)
          echo "Generated image tag: $image_tag"
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT

  build-tag-push:
    runs-on: ubuntu-latest
    needs:
      - generate-image-tag
    strategy:
      matrix:
        path:
          - 06-demo-application/api-golang
          - 06-demo-application/api-node
          - 06-demo-application/client-react
          - 06-demo-application/load-generator-python
          - 06-demo-application/postgresql
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
